1034 Remove Deprecated Abstract Class
Talent-Catalog/talentcatalog pull request #1035
Opened 2024-05-28 05:49 UTC by ajt001

https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/socket/EnableWebSocketSecurity.html

2024-07-17 03:19 UTC, camerojo reviewed
See comments.

Is there Spring standard migration doc which states that simply removing the deprected class in this way will have no side effects?

2024-07-17 03:19 UTC, camerojo commented on server/src/main/java/org/tctalent/server/configuration/WebSocketSecurityConfig.java
> -
How have you tested that there are no unexpected side effects introduced by dispensing with the deprecated class.

For example, is SameOrigin still disabled?

2024-07-24 09:07 UTC, ajt001 commented on server/src/main/java/org/tctalent/server/configuration/WebSocketSecurityConfig.java
> -
@camerojo The reference page is this:
https://docs.spring.io/spring-security/reference/servlet/integrations/websocket.html#websocket-sameorigin

My reading of it is that Spring adds extra security to protect cross domain access. 

> By default, Spring Security requires the [CSRF token](https://docs.spring.io/spring-security/reference/features/exploits/csrf.html#csrf) in any CONNECT message type. This ensures that only a site that has access to the CSRF token can connect. Since only the same origin can access the CSRF token, external domains are not allowed to make a connection.

So if you want to allow other domains to access the websocket, we can disable the protection and revert to the legacy Abstract class. 

I wasn't sure why you would want to have external domains connect this way - but given the code exists already to disable the security, I guess there is a reason?

2024-11-14 05:36 UTC, camerojo commented on server/src/main/java/org/tctalent/server/configuration/WebSocketSecurityConfig.java
> -
Yes - there is a reason. We are specific about the sites that can access. 

It is not clear how to replace the necessary configuration that we currently have (which took a while to get working) using the ill defined alternatives to the deprecated class.

So to be safe for now we will keep the deprecated approach - rather than trying to include it in our Spring Boot 3 upgrade. We can tackle the deprecation later - after we have successfully migrated to Spring Boot 3.

2024-11-14 05:37 UTC, camerojo requested changes
See comments - we will not do this now. Let's get the Spring upgrade completed first./

2024-11-19 04:39 UTC, camerojo commented
That has been addressed in #1614

2024-11-19 04:39 UTC, closed without merging