914 new job should be able to be created from a previous job acting as a job template
Talent-Catalog/talentcatalog pull request #1096
Opened 2024-06-12 01:52 UTC by cazcam34

The import changes are just changes to the correct import structure - as per our consistent import standard.

2024-06-14 14:33 UTC, camerojo requested changes
This PR is out of date with staging which means that changes appear for review which have already been reviewed and merged into staging.

To avoid this, and make the review process simpler, you should always merge your branch with staging before submitting a PR.

2024-06-17 01:43 UTC, cazcam34 commented
@camerojo sorry about that all done - merged updated staging into branch

2024-06-17 19:13 UTC, camerojo approved these changes

2024-06-17 19:13 UTC, camerojo commented
Just approved it! Now back to packing!

2024-06-18 01:40 UTC, merged