Built new link functionality for Quill Editor
Talent-Catalog/talentcatalog pull request #1256
Opened 2024-08-12 13:32 UTC by samschlicht

<img width="683" alt="Screenshot 2024-08-12 at 10 17 35 AM" src="https://github.com/user-attachments/assets/35acaa44-bf72-4550-8342-eebf3e3bb9ff">

<img width="396" alt="Screenshot 2024-08-12 at 10 17 09 AM" src="https://github.com/user-attachments/assets/0025f346-cbfa-4607-accf-65200fc5a143">

<img width="573" alt="Screenshot 2024-08-08 at 9 59 38 AM" src="https://github.com/user-attachments/assets/3b545217-320a-43dd-a139-bfd26c11d8f0">

2024-08-15 03:00 UTC, camerojo requested changes
See changes - hard coded English language text in candidate portal.

2024-08-15 03:00 UTC, camerojo commented on ui/candidate-portal/src/app/util/build-link/build-link.component.html
> +      <input type="text"
You need to use Keys for text in the candidate portal so that multilanguage is supported.

You can use the same key in the admin portal copy of this so that the admin portal and candidate portal versions are identical - but the admin portal will always be set to English

2024-08-16 13:39 UTC, samschlicht commented on ui/candidate-portal/src/app/util/build-link/build-link.component.html
> +      <input type="text"
@camerojo all done! 👍

2024-08-19 03:58 UTC, camerojo approved these changes, later dismissed
Approved

2024-08-19 03:58 UTC, camerojo commented
Don'y forget to add the English translations to Staging

2024-08-20 08:38 UTC, samschlicht commented
@camerojo sorry I had to resolve a new conflict, so this needs re-review! Nothing else changed.

Re staging translation, I've added it the release notes, so it definitely won't get missed. 😎

2024-08-20 09:04 UTC, camerojo submitted a review, later dismissed
Approved

2024-08-20 21:16 UTC, camerojo approved these changes
Approved

2024-08-21 08:47 UTC, merged