1450 keyword search in email and phone searches
Talent-Catalog/talentcatalog pull request #1451
Opened 2024-10-07 20:37 UTC by sadatmalik

This PR:

- Fixes a bug in search by phone/email
- Fixes a breaking unit test (server-side) related to daylight savings

The changes in this PR were already pushed to production as a Hotfix.

2024-10-08 04:04 UTC, camerojo requested changes
See comment.

Note that I think that a plain old 
like "%script%"

Works well on Postgres. Despite the wild cards at front and back. The email index on users is probably in memory and is fast.

2024-10-08 04:04 UTC, camerojo commented on server/src/main/java/org/tctalent/server/service/db/es/ElasticsearchServiceImpl.java
> +  private static final String EXTERNAL_ID_FIELD = "externalId.keyword";
Not sure what the problem is but this still doesn't work well in production.

For example - see this production screen. Partial matches are not working.

<img width="1658" alt="Screenshot 2024-10-08 at 2 56 35 PM" src="https://github.com/user-attachments/assets/ae03e1f2-20fe-4048-a026-5d37d1539c21">

Same goes for email addresses.

A search for yahoo.com.au or script doesn't come up with anything even though the email is

jadcpub-script@yahoo.com.au

2024-10-08 10:44 UTC, sadatmalik commented on server/src/main/java/org/tctalent/server/service/db/es/ElasticsearchServiceImpl.java
> +  private static final String EXTERNAL_ID_FIELD = "externalId.keyword";
This is now fixed and has been deployed to production as a hotfix. 

For partial phone numbers:

<img width="1248" alt="Screenshot 2024-10-08 at 11 39 40" src="https://github.com/user-attachments/assets/2a990478-7cb7-4c5e-94a3-970614874bc1">

And for partial email:

<img width="1249" alt="Screenshot 2024-10-08 at 11 41 05" src="https://github.com/user-attachments/assets/00fdd672-faeb-431b-8181-a74309111443">

Phone and email searches should use wildcard elasticsearch queries. Previously, they used prefix queries, which are inadequate and have now been corrected.

2024-10-08 23:12 UTC, camerojo approved these changes

2024-10-09 02:57 UTC, merged

2024-10-09 02:58 UTC, cazcam34 commented
Merged by @cazcam34 as other branches were relying on this test fix to be in staging so we can merge the other PRs