169 staging sandbox 2
Talent-Catalog/talentcatalog pull request #295
Opened 2023-09-05 09:09 UTC by samschlicht

Resubmitted PR — sets up env vars to toggle between staging and prod SF depending on which TC environment is running.

2023-09-05 09:15 UTC, samschlicht commented
@sadatmalik just a note that this is the resubmitted clean version — all my own code. 🙂

2023-09-06 11:49 UTC, sadatmalik requested changes

2023-09-06 11:49 UTC, sadatmalik commented on ui/admin-portal/src/app/model/base.ts
>    '.*/[\\w]+/[\\w]{15,}[^\\w]?.*';
These URL values are both the same - should one be prod and the other staging?

2023-09-09 20:22 UTC, sadatmalik submitted a review, later dismissed

2023-09-15 03:13 UTC, closed without merging