379 description field required when adding a job experience need better errorrequired indicator
Talent-Catalog/talentcatalog pull request #396
Opened 2023-10-26 23:49 UTC by cazcam34

Fixed the description bug but two additional things to note:

1. On the front end the validation for creating/updating a job experience is not consistent or present. So I added validation for description field to be required, however I thought it best to create a new issue for fixing up the validation on the other fields. 

2. I found another small but quite ugly bug where if there was a null field for the Contract Type & Employment Type fields, it was defaulting to displaying the equivalent as if the field was false. Thought I'd put in this bug fix branch as it's small and fairly nasty so best to do it in the hot fix.

2023-10-27 09:36 UTC, camerojo requested changes
See comment

2023-10-27 09:36 UTC, camerojo commented on server/src/main/java/org/tctalent/server/request/work/experience/CreateJobExperienceRequest.java
> +
This is just import order. Can you check your Intellij config

2023-11-01 15:52 UTC, camerojo approved these changes
See comments - better to fix HtmlSanitizer

2023-11-01 15:52 UTC, camerojo commented on server/src/main/java/org/tctalent/server/request/work/experience/UpdateJobExperienceRequest.java
> +        this.description = description != null ? HtmlSanitizer.sanitize(description) : null;
It would be much better to fix HtmlSanitizer.sanitize so that it handles null input.

2023-11-09 03:37 UTC, cazcam34 commented
Closed with another pull request here #417

2023-11-09 03:37 UTC, closed without merging